name: playit
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      macos:
        default_package: playit_dart_vlc
      windows:
        default_package: playit_dart_vlc
      android:
        default_package: playit_video_player

dependencies:
  flutter:
    sdk: flutter
  playit_common:
    path: ../playit_common
  playit_dart_vlc:
    path: ../playit_dart_vlc
  playit_video_player:
    path: ../playit_video_player
  audio_video_progress_bar: ">=0.9.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
