name: playit
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: playit_video_player
      macos:
        default_package: playit_dart_vlc
      windows:
        default_package: playit_dart_vlc

dependencies:
  flutter:
    sdk: flutter
  playit_common:
    path: ../playit_common
  playit_video_player:
    path: ../playit_video_player
  playit_dart_vlc:
    path: ../playit_dart_vlc

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
